DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
                      id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
                      name VARCHAR(255) NOT NULL,
                      created_at TIMESTAMP
);
CREATE TABLE url_checks (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            url_id BIGINT REFERENCES urls (id),
                            status_code INTEGER NOT NULL,
                            h1 VARCHAR(255),
                            title VARCHAR(255),
                            description TEXT,
                            created_at TIMESTAMP
);